---
- name: Create Cron Entry 
  hosts: all
  gather_facts: no
  become: true
  vars:
    ansible_ssh_private_key_file: /Users/holyswagger/.ssh/Test.pem
    ansible_user: ec2-user
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
  - roles/cron
